name: Atualizar README

on:
  push:
    paths:
      - '**.py'

permissions:
  contents: write

jobs:
  atualizar-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Executar script de atualização
        run: python update_readme.py

      - name: Commit e Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "🤖 Atualiza README com novos exercícios" || echo "Sem alterações"
          git push
